# Generated by Django 6.0 on 2025-12-06 00:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('confessions', '0007_comment_vote'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vote',
            name='value',
        ),
        migrations.AddField(
            model_name='comment',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='confessions.comment'),
        ),
    ]
