# Generated by Django 6.0 on 2025-12-19 19:15

import confessions.models
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('confessions', '0008_remove_vote_value_comment_parent'),
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('room', models.CharField(blank=True, max_length=255, null=True)),
                ('timestamp', models.DateTimeField()),
                ('notes', models.TextField(blank=True)),
                ('local_image', models.ImageField(blank=True, null=True, upload_to=confessions.models.report_upload_path)),
                ('remote_image', models.ImageField(blank=True, null=True, upload_to=confessions.models.report_upload_path)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
