# Generated by Django 6.0 on 2025-12-30 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('confessions', '0010_report_reported_user_report_reporter'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActivationCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=100, unique=True)),
                ('hardware_id', models.CharField(blank=True, max_length=255, null=True)),
                ('used', models.BooleanField(default=False)),
            ],
        ),
    ]
