# Generated by Django 6.0 on 2026-01-19 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('confessions', '0013_gradecalculation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gradecalculation',
            name='subjects_data',
            field=models.JSONField(default=dict),
        ),
    ]
